### ISSUE TITLE
Is there any plan to add AppStore Project?

### ISSUE THREAD

**Issue by tesths** [olucurious/Awesome-ARKit#38]
Today the Apple allow AR app sale in AppStore.
Is there any plan to add this app name and iTunes url?
It will be convenient for developer to experience real on sale AR app.

**Comment by sanzado** [comment]
I'm looking forward to it.

**Comment by tesths** [comment]
Also we can provide a planform for developer propaganda their app. And attract more people contribute to this repository.

**Comment by olucurious** [comment]
@tesths that's a very good suggestion

**Comment by olucurious** [comment]
@tesths @sanzado New AppStore category added

**Comment by olucurious** [comment]
I will be expecting your submissions

**Comment by tesths** [comment]
I think we also may formulate some AppStore Project submit rule.
Because we provide a place to propaganda, so we need more serious.
Just like as far as possible provide English version iTunes url and English description. Only this can make a more awesome propaganda and provide a unify discuss environment.
If provide other language version, it will be a little difficult to communicate, and it will be more mess. And maybe you can reject this pull request.

**Comment by olucurious** [comment]
@tesths I totally agree with, I'll add it to the contribution guideline

**Comment by tesths** [comment]
OK！After you add guideline, I will contribute😃

**Comment by olucurious** [comment]
@tesths check it out here: https://github.com/olucurious/Awesome-ARKit/blob/master/contributing.md
Is there something I'm missing?
