### ISSUE TITLE
How to save and load an object which was created by using ARKit ?

### ISSUE THREAD

**Issue by Tamil-Arya** [olucurious/Awesome-ARKit#40]
Hi guys, below scenario is possible or not ? 

**Scenario ::**  

- [ ] I want to create a object where i pointed by AR.
- [ ] I want to save SCNNode object which is created, I did by using NSUserdefaults.
- [ ] I want to show the object which is saved when i relaunching my app.

**Problems ::**

I have created an object where i need even i saved but the problem is, It creating everywhere when i relaunching my app. I want to be unique object as where i created at the same location.  

**What is my idea to solve this problem ::**

I was  getting device location (latitude,longitude) along AR giving distances from device  to object when i hit the screen. Also i did calculate the latitude and longitude of object place by using  longitude, latitude(device location) and distance. Afterwards, set the radius as 30m from device location then in b/w if any object was created recreated the SCNNode.

**Help ::** 

Is it possible to do, what i expected by using above idea ? If YES guide me How? :), if NO please guide me How ? :|  

![ar](https://user-images.githubusercontent.com/13419184/30698223-eba030c6-9efe-11e7-83cd-91cc4a5c4a1a.jpg)

**Comment by jarrillaga** [comment]
How do you solve this ?

**Comment by mariogithub1234** [comment]
You can Solve this bro?
