### ISSUE TITLE
Why this man can upload these apps to app store?

### ISSUE THREAD

**Issue by WorkerAmo** [olucurious/Awesome-ARKit#44]
APP Store search: HENGMAO LIU
https://itunes.apple.com/cn/app/ar量尺/id1269968846?mt=8
https://itunes.apple.com/cn/app/ar太阳系/id1270095769?mt=8
https://itunes.apple.com/cn/app/ar俄罗斯方块/id1276498269?mt=8
...

**Comment by nanospeck** [comment]
What is wrong in uploading?

**Comment by WorkerAmo** [comment]
Are you serious? He just copy the projects and upload to the app store without any change.

**Comment by arkilis** [comment]
This is really bad, better to put a comment on his "products".

**Comment by WorkerAmo** [comment]
He has removed some apps from app store.
