### ISSUE TITLE
ARPlanets - Solar system in AR 🌎  this project seems to be copied from me

### ISSUE THREAD

**Issue by miliPolo** [olucurious/Awesome-ARKit#71]
This project seems to be copied from me, you directly replace my project, this kind of practice is really disgusting, however the number of star is too few.I'm very disappointed with your behavior, and I really appreciate it before that.
In addition，I add a snapshot.
![251509075473_ pic](https://user-images.githubusercontent.com/11912376/32087006-6d62b894-ba9e-11e7-9be4-e68b387b5587.jpg)

https://github.com/miliPolo/ARSolarPlay

**Comment by olucurious** [comment]
Hi @miliPolo, I'm very sorry about what happened, I get a lot of submissions to go through everyday, I honestly thought you just made a Swift 4 version of the same project.
However, I am going to revert that particular PR until the appropriate credit is given to you in the swift project and I wouldn't allow a PR to overwrite your project.

Please Accept My Apologies.

**Comment by olucurious** [comment]
@miliPolo you should join the conversation in this PR: https://github.com/olucurious/Awesome-ARKit/pull/62
