### ISSUE TITLE
Recording AR Point Data or maybe Face AR Raw data

### ISSUE THREAD

**Issue by enzyme69** [olucurious/Awesome-ARKit#77]
Just curious, is there AR example out there that actually record the RAW data, whole 60 fps point cloud information in realtime from the iPhone and then save it to format that can be read at later stage back in computer? Thanks!

**Comment by AFathi** [comment]
Hey @enzyme69,

What do you mean by AR Point Data?

Like each camera buffer/frame and its detected key features or feature points in the AR space written to a local file so it can be parsed out later?
