### ISSUE TITLE
pls add Flotogram to App Store list.

### ISSUE THREAD

**Issue by luckybulldozer** [olucurious/Awesome-ARKit#82]
Flotogram
https://itunes.apple.com/us/app/flotogram/id1300137329
Time Kaleidoscope - Place your photos in Augemented Reality.  Animate them. Share them.

**Comment by olucurious** [comment]
You should send a pull request instead of creating an issue

**Comment by luckybulldozer** [comment]
I tried... I pushed.  Sorry.  Git is not my forte - as I am told far too often!
```remote: Permission to olucurious/Awesome-ARKit.git denied to luckybulldozer.
fatal: unable to access 'https://github.com/olucurious/Awesome-ARKit.git/': The requested URL returned error: 403```
